### PR TITLE
Much Improvements

### PR DESCRIPTION
**Pull request by fauzie811**
This PR includes:

- [x] Responsive toolbar
- [x] Realistic page style
- [x] Persistent "Pin Toolbar" setting
- [x] Other small improvements

Screenshot_20220108_092803

Screenshot_20220108_092840

Screenshot_20220108_092921

### CODE REVIEW

**Comment by mr-islam** [comment]
As salamu alaykum,

Amazing, thank you so much! 🌹💚

I am downloading your changes now to test, inshaAllah I will let you know any feedback soon

Then we can merge and release the update inshaAllah

**Comment by mr-islam** [comment]
Sorry, I was trying to build your fork to test, but there's some problem on my windows

Could you please maybe send me a packaged .exe install for this PR? Thank you @fauzie811

**Comment by fauzie811** [comment]
https://mega.nz/file/VIFzyQwB#bDEuinjdglKUki1CJRrbFeM3_7ReWJ4hAFvrJQEJxxc

I haven't tested it on Windows. I compiled using Wine on Linux.

**Review by mr-islam — APPROVED** [review]

**Review by mr-islam — APPROVED** [review]

**Comment by mr-islam** [comment]
Thank you for doing all that! 

Alhamdulillah I just tested and it all looks good mashaAllah 👍

The code changes are also very good and fix a lot of issues and bad code, thank you!

Jazakumullahu khayran 💚

**Pull request merged**
